In [3]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


2.17.0


In [5]:
#one dimension tensor 
tensor_id = np.array([1.3,1,4.0,23.99])
print(tensor_id)

[ 1.3   1.    4.   23.99]


In [6]:
print(tensor_id[0])


1.3


In [7]:
print(tensor_id[2])

4.0


In [8]:
import numpy as np
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
tensor_2d[3][2]

14

In [15]:
#Tensor Handling and Manipulations
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype="int32")
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype="int32")
print(matrix1)
print(matrix2)
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1,matrix2)
print("Product: ",matrix_product)

matrix_sum = tf.add(matrix1,matrix2)
print("Sum: ",matrix_sum)

matrix_substract = tf.math.subtract(matrix1,matrix2)
print("subtraction: ",matrix_substract)

matrix_division = tf.math.divide(matrix1,matrix2)
print("division: ",matrix_division)


matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype="float32")
print(matrix_3)

a = (9)
b = (10)
#printing the input  tensor
print("a: ",a)
print("b: ",b)

#finding truth value 
res= tf.math.less(x=a,y=b)

#printing the result 
print("Result: ",res)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Product:  tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32)
Sum:  tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)
subtraction:  tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)
division:  tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float64)
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
a:  9
b:  10
Result:  tf.Tensor(True, shape=(), dtype=bool)
